### ISSUE TITLE
Port ocaml-bimage to lablgtk3 

### ISSUE THREAD

**Issue by XVilka** [zshipko/ocaml-bimage#1]
GTK 2 is being deprecated, and there is largely compatible version of OCaml bindings to GTK 3 is available - [lablgtk3](http://opam.ocaml.org/packages/lablgtk3/).

See lablgtk3 branch here: https://github.com/garrigue/lablgtk/tree/lablgtk3

**Comment by zshipko** [comment]
Thank you, I will look into fixing this when I get a moment!
