### ISSUE TITLE
Examples of using Expr.Transform?

### ISSUE THREAD

**Issue by sremedios** [zshipko/ocaml-bimage#10]
For example, I would like to simply rotate an image by 45 degrees. 
I can easily open the image, but I don't know how to apply the transform.

Are there any clear examples on how to use the API to do this?

**Comment by zshipko** [comment]
There aren't any examples in the repo right now, I will be making some updates soon so will try to add one to the `examples` folder.

Something like this should work:

```
let transform = Expr.rotate (Angle.of_degrees 45.) in
let output = Filter.run_expr ~output (Input.of_image input) transform in
...
```

Where `input` is your input image and `output` is your output image.

The general idea is that you take an `Expr.t` and either convert it to a `Filter.t` using `Filter.v` or execute it directly using `Filter.run_expr` or `Filter.eval_expr`

**Comment by sremedios** [comment]
Thank you for this example! This definitely clarifies the general use case of your library for me. So in summary: it's intended that we compose a series of transforms as expressions, convert them to filters, and then ultimately run them via the `Filter` API, yes?

**Comment by zshipko** [comment]
Yep, that’s correct!
