### ISSUE TITLE
Example(s) not working

### ISSUE THREAD

**Issue by klartext** [zshipko/ocaml-bimage#6]
Tried one of the examples (the one with Magick.read).

Does not compile:

```
File "bsp.ml", line 12, characters 22-24:
12 | let f = Op.(grayscale &- scalar 0.5) in
                           ^^
Error: Unbound value &-
```

**Comment by klartext** [comment]
Would also be good to have the examples directly in the repo as code.

**Comment by zshipko** [comment]
Thanks for letting me know - I should have some time to fix this over the weekend.

That line should be something like this instead:
```
let f = let open Op in Infix.(grayscale &- scalar 0.5) in
...
```

**Comment by zshipko** [comment]
I ended up having some time this morning, so I cleaned up the readme examples and added them to the repo: https://github.com/zshipko/ocaml-bimage/tree/master/examples
